### ISSUE TITLE
Prototype Pollution

### ISSUE THREAD

**Issue by DaveNorth866** [HendrikRoth/node-red-contrib-oled#13]
HI when I installed node-red-contrib-oled on ...
Raspberry pi with..
node-red 0.20.6
nr dashboard 2.15.5
stretch v9 
node -v 10.16.0 
I installed via cmd line but same result if install via manage palette.
I get ... found **100 vulnerabilities (12 low, 5 moderate, 83 high)**
run `npm audit fix` to fix them, or `npm audit` for details

npm audit fix   does not resolve issue
npm audit   reveals that all are attributed to node-red-contrib-oled  see attached file for details
[node-red-contrib-oled.txt](https://github.com/HendrikRoth/node-red-contrib-oled/files/3481375/node-red-contrib-oled.txt)

Incidentally the oled node & oled works great but from what I read these vulnerabilities need to be fixed in the underlying code.

Please advise thanks.

**Comment by HendrikRoth** [comment]
#23
