### ISSUE TITLE
strange situation

### ISSUE THREAD

**Issue by connected201** [HendrikRoth/node-red-contrib-oled#20]
hi, i have classic display SSD1306 like this: 
![image](https://user-images.githubusercontent.com/20506433/83333236-2b20d980-a2a8-11ea-9f64-1b48061c07c2.png)
i connected to RPI. all working ok in nodered!
if i run i2cdetect -y -a 1, i receive i2c adress (3c)

but i bought another display https://www.electrodragon.com/product/1-3-oled-display-mini-shield-for-raspberry-pi/
1. this module not working in node-red.
2. this module not seen with i2cdetect -y -a 1.
but i playing on this module using https://github.com/Edragon/RPI/tree/master/Display/1.3-OLED-SH106/Python and all work fine!
question: how i can use this module in nodered?
in nodered i have error with 3c adress ("TypeError: Cannot read property 'setCursor' of undefined")
with classic display all ok.

**Comment by matmai** [comment]
Do you really use I2C and not SPI?

Description of your displays says:
> Default wiring option is 4-SPI, if you want to use IIC or 3-SPI, you must cut off the lines first.

And the [Python library](https://github.com/Edragon/RPI_Display/blob/main/1.3-OLED-SH106/Python/demo.py) also supports SPI, so this could be the cause that it is working there.
