### ISSUE TITLE
Instructions to get this to work for some people

### ISSUE THREAD

**Issue by Cyberwhip1984** [HendrikRoth/node-red-contrib-oled#21]
After 3 days trying to get this module to work on raspberry pi, I finally have the solution after modifying the package.json on my own, at some point this could potentially break something, but working solution for now.

This looks like alot of work but it is about 15 to 20 minutes of effort.

1st install the 3 depeendancy modules:
npm i i2c-bus     (this took some effort also but 5.2.0 finally installed)
npm i oled-i2c-bus
npm i oled-font-5x7

after successful installation of all 3, then do
npm list i2c-bus
npm list oled-i2c-bus
npm list oled-font-5x7
 make note of the versions that are installed for each module, 
examples from my case = i2c-bus@5.2.0, oled-i2c-bus@1.0.11, oled-font-5x7@1.0.3

then download the node-red-contib-oled from here.
on your pc edit the package.json.  Change the dependant module version numbers to match your installed.
copy the entire package to your device, raspberry pi in my case
stop node red if it is running
then go into the node red directory, ex = cd home/pi/.node-red or cd ~/.node-red
then do an install of the updated files, npm i path_name_here/node-red-contib-oled
start node red, new nodes should be there now if everything was successful in install/

Regards
Bill Hall

**Comment by Nestornp** [comment]
i2c-bus, oled-i2c-bus and oled-font-5x7 needs to be installed in node red folder???
I have followed your steps, with the package.js modified, the package appears in the node red packages menu with an exclamation point, and the nodes do not appear in the nodes menu.

**Comment by Cyberwhip1984** [comment]
It's really hard to say, this is only what I did to make it work for me.  I'm not an expert in node red, so i'm not real familiar with the exclamation error.  You should not have to copy or move the 3 dependent packages, only first install them in node red.  If there is an error installing the 3 dep nodes then contrib-oled won't work either.

is there an error message or log when you try to install the contrib-oled node?

I had a really hard time to get i2c-bus installed, maybe that is the problem.  Did you do the list command for each module after installing the three modules?

did you update and install the updated package file correctly?

it's also possible that there is a new version one of the dependency files that has broken code.  Maybe you can install the versions I have listed.

> 
> 
> i2c-bus, oled-i2c-bus and oled-font-5x7 needs to be installed in node red folder???
> I have followed your steps, with the package.js modified, the package appears in the node red packages menu with an exclamation point, and the nodes do not appear in the nodes menu.

**Comment by HendrikRoth** [comment]
#23
