### ISSUE TITLE
Dependencies version updated

### ISSUE THREAD

**Issue by VIechristoffersen** [HendrikRoth/node-red-contrib-oled#23]
I did a pull request and updated this for your review.

inside package.json dependency version # are off.  Below worked for me.

{
  "name": "node-red-contrib-oled",
  "version": "0.2.0",
  "description": "Node-Red node for controlling OLED displays",
  "main": "index.js",
  "scripts": {},
  "repository": {
    "type": "git",
    "url": "git+https://github.com/HendrikRoth/node-red-contrib-oled.git"
  },
  "keywords": [
    "node-red"
  ],
  "author": "Hendrik Roth <hi@hendrikroth.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/HendrikRoth/node-red-contrib-oled/issues"
  },
  "homepage": "https://github.com/HendrikRoth/node-red-contrib-oled#readme",
  "dependencies": {
    "i2c-bus": "^5.2.0",
    "oled-font-5x7": "^1.0.3",
    "oled-i2c-bus": "^1.0.11"
  },
  "node-red": {
    "nodes": {
      "oled": "oled.js"
    }
  }
}

**Comment by DaveNorth866** [comment]
I can verify VIechristoffersen comment

"i2c-bus": "^5.2.0",
"oled-font-5x7": "^1.0.3",
"oled-i2c-bus": "^1.0.11"

are the correct settings and work fine for me, node-red v1.1.3

**Comment by Ataraxiall** [comment]
verified too, the original dont work.
