### ISSUE TITLE
npm install node-red-contrib-oled    does not install latest code (0.1.0)

### ISSUE THREAD

**Issue by Toshibass** [HendrikRoth/node-red-contrib-oled#3]
HendrikRoth

Although code has been updated to "version": "0.1.0" which incidental works very well .... Node-Red Manage Palette still says "0.0.2" is latest update and if you install via Manage Palette or npm install node-red-contrib-oled you still get "0.0.2" not "0.1.0"

**Comment by HendrikRoth** [comment]
updated all repositories, now everything is on 0.1.0
