### ISSUE TITLE
package.json mismatch between npm and github

### ISSUE THREAD

**Issue by mschm** [HendrikRoth/node-red-contrib-oled#5]
Hi, I noticed that the installation of the npm package comes with a ton of dependencies, caused by `update` module. That dependency does not not show up in the github repo version of the package.json, but only in the npm package:
```
...
"dependencies": {
    "i2c-bus": "^1.2.4",
    "oled-font-5x7": "^1.0.0",
    "oled-i2c-bus": "^1.0.10",
    "update": "^0.7.4"
  }
...
```

What's up with that?

**Comment by HendrikRoth** [comment]
do you use an old npm version? npm adds the update package to force the user to update its npm package manager:

> As of npm@5.0.0, the npm update will change package.json to save the new version as the minimum required dependency.

https://docs.npmjs.com/cli/update
 

>

**Comment by mschm** [comment]
that's an interesting fact, thank you. and apologies for my misleaded guess ;)

i was running node-red in docker on a pi zero, using the current image `nodered/node-red-docker:rpi`. that actually comes with node 6 and an old npm version.
for some reason (which i haven't examined any further) the installation failed at the `update` module. switching to the docker image `nodered/node-red-docker:rpi-v8` will probably fix that, but i wasn't able to test it yet.

by the way – thank you for this node! after i managed to install it without `update` it worked well with the adafruit 128x64 oled bonnet on a pi zero.
