### ISSUE TITLE
Is it possible to use sh1106 oled screens with this?

### ISSUE THREAD

**Issue by DeviousPenguin** [HendrikRoth/node-red-contrib-oled#7]
I've tried a ssd1306 oled screen and it works great, but I also have a few sh1106 oled screens that I'd like to use also. I've tried connecting up a sh1106 screen and while it does produce pixels on the screen, it looks like white noise, I'll attach a screenshot:

![20180703_182524](https://user-images.githubusercontent.com/11376139/42283233-c77f1152-7fa0-11e8-98ea-d65d729f8dd2.jpg)

I've testing this screen using the python Luma module, and it does work, but you need to set the device to sh1106, is there a way of doing this within NodeRED?

Thanks

**Comment by HendrikRoth** [comment]
This lib depends on https://github.com/baltazorr/oled-i2c-bus
Please check, if your screen is supported.
